name: DesignLab
favicon: null
layout_spectrum: 0.5437714201398194
typography_spectrum: 0.4195549900177866
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.41344093019142747
  lightness: 0.8492731978185475
  saturation: 0.6144400795456022
  rhythmicContrast: 0.6368593487422913
purpose: []
