name: DesignLab
favicon: null
layout_spectrum: 1
typography_spectrum: 0.22455
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78ab37'
    - '#b3b3b3'
    - '#f7f4f5'
    - '#b2f400'
    - '#003300'
  brandStrength: 0.41344093019142747
  lightness: 0.8492731978185475
  saturation: 0.6144400795456022
  rhythmicContrast: 0.6368593487422913
purpose: []
